name: Build, Test and Analyze (React & .NET)

# Define variables available to all jobs in the workflow
env:
  FRONTEND_DIR: ./src/nimblist/Nimblist.Frontend                # Directory for React app
  DOTNET_DIR: ./src/nimblist                        # Directory containing .sln (use '.' if root, or e.g., ./backend)
  DOTNET_SLN: nimblist.sln           # Name of the .NET solution file
  # Define full report paths relative to the repository root
  FRONTEND_COVERAGE_PATH: ./src/nimblist/Nimblist.Frontend/coverage/lcov.info
  DOTNET_COVERAGE_PATH: ./src/nimblist/Nimblist.test/TestResults/Coverage/coverage.opencover.xml # Adjust if DOTNET_DIR is not root or output changes
  PYTHON_DIR: ./src/nimblist/Nimblist.classification # Directory for Python classification service
  PYTHON_COVERAGE_PATH: ./src/nimblist/Nimblist.classification/coverage.xml # Path for Python coverage report
  VITE_API_BASE_URL: https://localhost:64213
  # --- SonarQube Configuration (Non-Secret) ---
  SONAR_PROJECT_KEY: "tmnrtn_nimblist"     # <-- ADD THIS (Replace with actual value)
  SONAR_ORGANIZATION: "tmnrtn" # <-- ADD THIS (Replace with actual value)
  SONAR_HOST_URL: "https://sonarcloud.io"   
  API_IMAGE_NAME: lankykowalski/nimblist-api # Replace with your Docker Hub username/repo
  FRONTEND_IMAGE_NAME: lankykowalski/nimblist-frontend # Replace
  CLASSIFICATION_IMAGE_NAME: lankykowalski/nimblist-classification # Python classification service

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_test_analyze:
    name: Build, Test & Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --- Node.js/React Setup & Test ---
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ${{ env.FRONTEND_DIR }}/package-lock.json

      - name: Install Node dependencies
        run: npm ci
        working-directory: ${{ env.FRONTEND_DIR }}

      - name: Run React Linters (Optional)
        run: npm run lint
        working-directory: ${{ env.FRONTEND_DIR }}
        
      - name: Run React unit tests and generate coverage report
        run: npm run test:coverage
        working-directory: ${{ env.FRONTEND_DIR }}

      # --- Python/Classification Service Setup & Test ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: ${{ env.PYTHON_DIR }}/requirements.txt

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8
        working-directory: ${{ env.PYTHON_DIR }}

      - name: Run Python linting
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        working-directory: ${{ env.PYTHON_DIR }}

      - name: Run Python tests with coverage
        run: |
          pytest --cov=. --cov-report=xml:${{ github.workspace }}/${{ env.PYTHON_COVERAGE_PATH }} --junit-xml=${{ github.workspace }}/src/nimblist/Nimblist.classification/test-results.xml
        working-directory: ${{ env.PYTHON_DIR }}

      # --- .NET Setup & Test ---
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore .NET dependencies
        run: dotnet restore ${{ env.DOTNET_SLN }}
        working-directory: ${{ env.DOTNET_DIR }}

      # 1. Install the .NET Sonar Scanner tool
      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      # 2. Begin SonarScanner analysis (BEFORE build/test)
      - name: Begin SonarQube Scan
        working-directory: ${{ env.DOTNET_DIR }}
        run: |
          dotnet sonarscanner begin /k:"${{ env.SONAR_PROJECT_KEY }}" /o:"${{ env.SONAR_ORGANIZATION }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ env.SONAR_HOST_URL }}" /d:sonar.test.inclusions="**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx,**/*Tests.cs,**/*_test.py,**/test_*.py" /d:sonar.exclusions="**/obj/**,**/bin/**,${{ env.FRONTEND_DIR }}/node_modules/**,**/*.Generated.cs,**/nimblist.data/Migrations/**,**/nimblist.api/Areas/**,**/nimblist.api/Program.cs" /d:sonar.javascript.lcov.reportPaths="${{ github.workspace }}/${{ env.FRONTEND_COVERAGE_PATH }}" /d:sonar.cs.opencover.reportsPaths="${{ github.workspace }}/${{ env.DOTNET_COVERAGE_PATH }}" /d:sonar.python.coverage.reportPaths="${{ github.workspace }}/${{ env.PYTHON_COVERAGE_PATH }}" /d:sonar.python.xunit.reportPath="${{ github.workspace }}/src/nimblist/Nimblist.classification/test-results.xml"

      # 3. Build the solution (AFTER scanner begin)
      - name: Build .NET solution
        run: dotnet build ${{ env.DOTNET_SLN }} --configuration Release --no-restore
        working-directory: ${{ env.DOTNET_DIR }}

      # 4. Run tests (AFTER scanner begin, usually AFTER build)
      - name: Run .NET tests and generate coverage report
        run: >
          dotnet test ${{ env.DOTNET_SLN }} --no-build --configuration Release -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:CoverletOutput=${{ github.workspace }}/${{ env.DOTNET_COVERAGE_PATH }}
        working-directory: ${{ env.DOTNET_DIR }}

      # 5. End SonarScanner analysis (AFTER build/test)
      - name: End SonarQube Scan
        working-directory: ${{ env.DOTNET_DIR }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner end /d:sonar.login="${{ env.SONAR_TOKEN }}"

  publish:
    name: Publish Docker Images
    needs: build_test_analyze
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- Login to Docker Hub ---
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- Build and Push Images (using Docker Hub names) ---
      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOTNET_DIR }}/nimblist.api/Dockerfile
          push: true
          tags: |
            ${{ env.API_IMAGE_NAME }}:latest
            ${{ env.API_IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.FRONTEND_DIR }}/Dockerfile
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE_NAME }}:latest
            ${{ env.FRONTEND_IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # --- Build and Push Classification Service Image ---
      - name: Build and push Classification Service image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/nimblist/Nimblist.classification/Dockerfile
          push: true
          tags: |
            ${{ env.CLASSIFICATION_IMAGE_NAME }}:latest
            ${{ env.CLASSIFICATION_IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
